baseURL = "https://raphelwei.netlify.app/"
languageCode = "en-us"
title = "Example YinYong Blog"
theme = "yinyang"
DefaultContentLanguage = "en"

[params.author]
  name = "Joway Wang"
  homepage = "https://joway.io/"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
disqus = "joway" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "Categories"
link = "/posts"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://joway.io"